# Generated by Django 5.1 on 2024-08-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
